### ISSUE TITLE
Correctly create the EFS share symlink on the XFCE desktop

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ansible-role-xfce-cool#17]
# 🐛 Summary #

The symlink to the EFS share that is being created on the XFCE desktop is borked.  Even after you `chown` the file share the icon has a little lock on it, and @nickviola and other PCA assessors reported that they are unable to drag-and-drop files directly onto it.  The Xfce graphical desktop simply does not refresh the symlink icons on the user's desktop, and therefore it does not allow drag-and-drop when it becomes possible later.  

As a temporary workaround, one _can_ double-click the symlink, which opens a file explorer window where files can be dragged-and-dropped.  Destroying and recreating the symlink also fixes the problem.

The symlink is currently being created by `xdg-autostart` when the graphical environment is initialized.  Given that the symlink would also be useful from a terminal, I think it makes more sense to generate it via a `systemd` user service.  Doing it this way also makes it easy for the user to force the recreation of the symlink with a `systemctl --user restart <service_name>` command.

## To reproduce ##

1. Log into an XFCE desktop for any instance type in the COOL via Guacamole.
1. Manually change teh permissions on the file share via `sudo chown -R vnc:vnc /share`.
1. Try to drag any file onto the "Share" icon that is located on the XFCE desktop.
1. Observe that the attempted drag-and-drop/copy fails.

## Expected behavior ##

I would expect the symlink to allow drag-and-drop after the `chown` command.

**Comment by nickviola** [comment]
Thanks for your help with this @jsf9k! Let me know if there is anything I can do to help.
